# Generated by Django 5.0.3 on 2024-03-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A', models.IntegerField()),
                ('B', models.IntegerField()),
                ('C', models.IntegerField()),
                ('Price', models.IntegerField()),
            ],
        ),
    ]
