# Generated by Django 5.0.3 on 2024-04-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0002_marketingdata2'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingData3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('width', models.IntegerField()),
                ('length', models.IntegerField()),
                ('height', models.IntegerField()),
                ('price', models.IntegerField()),
                ('frame_type', models.CharField(max_length=3)),
                ('roof_type', models.CharField(max_length=25)),
                ('wall_type', models.CharField(max_length=25)),
                ('roof_panels', models.CharField(max_length=25)),
                ('wall_panels', models.CharField(max_length=25)),
                ('membrane', models.CharField(max_length=25)),
                ('snow', models.CharField(max_length=3)),
                ('wind', models.CharField(max_length=3)),
            ],
        ),
    ]
