# Generated by Django 5.0.3 on 2024-05-23 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counterparty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counterparty', models.CharField(max_length=250)),
                ('debit', models.BigIntegerField()),
                ('credit', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='accountingentries',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.counterparty'),
        ),
    ]
