# Generated by Django 5.0.3 on 2024-05-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0002_counterparty_alter_accountingentries_counterparty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counterparty',
            name='credit',
        ),
        migrations.RemoveField(
            model_name='counterparty',
            name='debit',
        ),
        migrations.AddField(
            model_name='counterparty',
            name='accounts_payables',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='accounts_receivables',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='advances_paid',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counterparty',
            name='advances_received',
            field=models.BigIntegerField(default=1),
            preserve_default=False,
        ),
    ]
