# Generated by Django 5.0.3 on 2024-05-24 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0003_remove_counterparty_credit_remove_counterparty_debit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountingentries',
            name='counterparty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounting_entries', to='accounting.counterparty'),
        ),
    ]
